### ISSUE TITLE
Creating 2 Devices under Same "Friendly Name"

### ISSUE THREAD

**Issue by UberSlackr** [dhleong/wemore#11]
When Alexa is asked to "discover devices" she finds 2 new devices.. I currently only have 1 WeMor node setup, but Alexa is finding 2. They both appear under the same "Friendly Name." One is showing in Alexa as a "Wemo Plug" the other shows as "Wemo Switch."

I've tried deleting the node, and removing the devices from Alexa. Then adding a new wemore node. Same result. 2 Discovered devices, 1 friendly name, one Switch, the other Plug.

**Comment by dhleong** [comment]
What do you mean "wemore node"? Do you have any code to show what you're doing? If you're referring to the device emulation API, Wemore should just advertise whatever friendly name you specify.

**Comment by UberSlackr** [comment]
Yes the WeMo Emulator node in Node-Red.

What code would you like? Its a Node in a Node-Red flow.
```
[
    {
        "id": "bf47c683.556d18",
        "type": "wemo-emulator",
        "z": "954f11bb.0fa6f",
        "name": "WeMo Test",
        "friendlyName": "Wemo Test",
        "serial": "node-red-wemo1",
        "port": "2001",
        "onTopic": "msg",
        "onPayload": "on",
        "offTopic": "msg",
        "offPayload": "off",
        "x": 330,
        "y": 252,
        "wires": [
            []
        ]
    }
]
```

And in the Amazon Alexa app, under "Smart Home" it shows device "Wemo Test" (WeMo Switch) "WeMo Test" (WeMo Plug)

![image](https://user-images.githubusercontent.com/4933069/33348569-7edae510-d45c-11e7-85ca-899ce5a18010.png)

**Comment by dhleong** [comment]
Sorry, I have nothing to do with node-red. You'll have to report the issue
with them.

**Comment by UberSlackr** [comment]
Node-Red dev didn't make the node. And this git is linked in the description of the node info.

**Comment by dhleong** [comment]
I don't doubt it depends on this project, but as I didn't develop the node, there's nothing I can do to fix it. I don't use Node-Red or anything related to it for my home automation; I use this project directly, and don't have any problems like the one you've described, so it must be a problem with the implementation of the node you're using.

**Comment by dhleong** [comment]
You might be looking for this: https://github.com/biddster/node-red-contrib-wemo-emulator
