### ISSUE TITLE
How to pair emulated devices with wemo app?

### ISSUE THREAD

**Issue by TECHNOFAB11** [dhleong/wemore#12]
The app wants me to connect to the wemo's wifi. But wemore doesnt have a wifi. How can i connect them, so that i can use them with the google home? I just want to control fhem with my google home, and this is the only way without using IFTTT and to disable my firewall for fhem (is an option, but an unsecure one). Please help

**Comment by TECHNOFAB11** [comment]
Or is there any way to control a raspberry or directly fhem with the google home / assistant

**Comment by dhleong** [comment]
Unfortunately, wemore's device emulation isn't compatible with Google Home. It just emulates devices on the local network, which Amazon's Alexa and a few other home automation systems can detect. Sadly, Google Home seems to only talk directly to cloud-based services. I haven't yet figured out how Wemo devices "phone home" to be registered with Wemo cloud.

Sorry!
