### ISSUE TITLE
Identify the callee 

### ISSUE THREAD

**Issue by biddster** [dhleong/wemore#13]
Is there anyway to identify the callee in wemore. 

For example, I have 2 amazon echos. I'd like to be able to identify which echo invoked wemore.

Is that possible?

**Comment by dhleong** [comment]
I suspect the only information we'll get about the callee is their IP address, via the TCP connection. We could emit an extra object with the on/off/state events that includes this, but you would probably be on your own to deal with the IP address. Would that be enough?

**Comment by biddster** [comment]
I think it would yes, that would be perfect.

**Comment by dhleong** [comment]
Released as 0.5.0. See the README for more information. Note that for historical reasons there is a "self" object emitted as well, so for `on` and `off` you'll get `(self, sender)`, and for `state` you'll get `(binaryState, self, sender)`.

**Comment by biddster** [comment]
Many thanks.
