### ISSUE TITLE
There is a possible mistake in emulate.js

### ISSUE THREAD

**Issue by AlGu1** [dhleong/wemore#14]
Hi,

i am using this Lib by [biddster/node-red-contrib-wemo-emulator](https://github.com/biddster/node-red-contrib-wemo-emulator). And die node-red in my ioBroker to emulate devices from my homeautomation for Amazon Alexa.
I have installed the lib "node-red-contrib-wemo-emulator" in my node-red and using it over Alexa speech control, that works fine. But in the Alexa App i can not control the device. It shows "Belkin International Inc." and loading icon. But when i change the row 178 in emulate.js into:
`UDN: "uuid:" + this.serial`
then can i control the device in the Alexa App.

I think it is a bug, but i can not check it in your using of this lib.

Thanks
AlGu

**Comment by AlGu1** [comment]
Ok mhh...but is the UDN with "uuid:" not the correct code?! Other emulations like [node-red-contrib-alexa-local](https://github.com/originallyus/node-red-contrib-alexa-local/blob/master/setup.xml) use it so.
Greetings
AlGu

**Comment by dhleong** [comment]
It seems to work for me without it. I would want a proper UUID if I'm going to prefix with `uuid:`; the serial number we're generating is definitely not a UUID.

**Comment by jtai** [comment]
FWIW I ran into the same issue as @AlGu1 using wemore directly. I was previously using https://github.com/kakopappa/arduino-esp8266-alexa-multiple-wemo-switch to emulate switches, which worked just fine. When I switched to wemore the alexa app hung as described above. Changing the UDN to prefix with `uuid` made it work.

From reading through issues like https://github.com/kakopappa/arduino-esp8266-alexa-multiple-wemo-switch/issues/22, it sounds like different versions of echo hardware behave differently, which may account for the difference in experiences?

**Comment by dhleong** [comment]
Thanks for the report @jtai, that's very interesting. Would you mind testing with generating an actual UUID to be used after `uuid:` with something like [UUID v4](https://www.npmjs.com/package/uuid)? If that still works for you then I'll be happy to verify that it still works on my setup and, assuming it does, implement it into the library.

**Comment by jtai** [comment]
Alexa seems ok with the UUID, at least on my echo. This works: https://github.com/jtai/wemore/commit/cd374c680897f867bb419c13b9a2cfa15c9f5096

**Comment by dhleong** [comment]
Hello everyone, thanks for your help here! I've released version 0.6.0 that uses the `uuid:` prefix. Please give it a try and let me know if it works for you!
