### ISSUE TITLE
Added a function to update the status of emulated devices?

### ISSUE THREAD

**Issue by piznel** [dhleong/wemore#17]
Hello,
Is it possible to add a function to update the status of a virtual device?
Because I use your library by coupling it with a home automation application, and that would allow me to be synchronized between Alexa and the application.
Thank you!

**Comment by dhleong** [comment]
You mean just change Wemore's internal state so a "toggle" command sent to it works as expected? There's a property `.binaryState` on the device instance; just set it to `1` (on) or `0` (off).

**Comment by piznel** [comment]
thank you for your very quick answer:)

So that means that, using the example of emulated TV in your readme:
`tv.binaryState = 1`
will update the TV status in Alexa?

I also have a small problem with the example you give next:
```
tv.on('state', function(binaryState, self, sender) {
    console.log("TV set to=", binaryState);
    tv.close(); // stop advertising the device
});
```
What's the point? I read all your code, but I couldn't find the broadcast of the state event.

Thank you in advance!

**Comment by piznel** [comment]
Thanks !
