### ISSUE TITLE
use of "dhleong/node-ssdp#2d8dcfa" causes DTrace provider errors on Mac OS X

### ISSUE THREAD

**Issue by hjespers** [dhleong/wemore#2]
Using "node-ssdp": "dhleong/node-ssdp#2d8dcfa" throws DTrace errors on Mac OS X 

{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

This appears to be fixed in node-ssdp 2.7.0 from https://github.com/diversario/node-ssdp

**Comment by dhleong** [comment]
Closed by PR #3
