### ISSUE TITLE
request js dep is missing?

### ISSUE THREAD

**Issue by biddster** [dhleong/wemore#4]
Just npm installed and upon running the Readme sample, it threw an exception about request being missing. I cd'd into node_modules/wemore and did npm install request --save. Now all is well and the sample runs.

**Comment by dhleong** [comment]
Are you trying to do `npm install -g wemore` to get the `wemore-toggle` cli command, or `npm install --save` to add as a dependency to a project? Either way it worked fine for me just now.

**Comment by biddster** [comment]
I was installing it as a dep. Let me experiment more and get back to you.

**Comment by biddster** [comment]
Bizarre, it's working now, duff network call maybe? Either way, have a great weekend, closing.
